xcodeproj 'Campus-Cruises.xcodeproj/'

# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Campus-Cruises' do
    pod 'GoogleMaps'
end

target 'Campus-CruisesTests' do

end

target 'Campus-CruisesUITests' do

end

